### ISSUE TITLE
Support for jsx and tsx

### ISSUE THREAD

**Issue by jayasurian123** [bluestar55/vscode-hide-top-comment#2]
Hi,

Could you also support jsx and tsx extensions also? Since the comment is same as JS,  I guess it would be a relatively easy change 

thanks a lot :)

**Comment by jayasurian123** [comment]
Any spare time to support this? :)

**Comment by bluestar55** [comment]
I hope I can find time. Do you need any more extension other than .jsx and .tsx?

**Comment by jayasurian123** [comment]
Thats all needed as of now! 
Next time I will try to raise the PR for same. Need to learn a bit how to write the vs extension :)

**Comment by jayasurian123** [comment]
thank you 🙏🏼
