### ISSUE TITLE
Ruby support

### ISSUE THREAD

**Issue by mediafinger** [bluestar55/vscode-hide-top-comment#3]
Hey,

a colleague of mine suddenly started to annotate all our model and factory files... long story short, I only see comments now instead of code. While looking for a practical solution, I've stumble over this extension. Unfortunately is does not have **Ruby** support built-in. 

## Blocks of single-line comments

I assume you could easily use the same logic as for Python - at least to remove a block of single-line comments. I've added an example of my "issue" below:

```ruby
# == Schema Information
#
# Table name: users
#
#  id                       :uuid             not null, primary key
#  email                    :string           not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#
class User < ApplicationRecordWithUuidv7
  has_secure_password

  def a_method
    puts "Hello"
  end
end
```

## Bonus: multiline-comments

Ruby has support for multi-line comments as well. They are rather unpopular, but some tools might generate them. The syntax is described here:

* https://docs.ruby-lang.org/en/master/syntax/comments_rdoc.html

## Noise reduction

I've you'll add support, I will try to convince the maintainers of this comment creation machine to list your extension as a relief for people who see these kind of comments mostly as noise:

* https://github.com/ctran/annotate_models

**Comment by bluestar55** [comment]
Hi, I added support for Ruby inline comments. Thank you for your suggestion.
